# Generated by Django 3.1.2 on 2020-10-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_lineitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
